import { createContext, useContext, useEffect, useMemo, useState } from 'react';
import type { ReactNode } from 'react';

export type Language = 'en' | 'bn';

const translations: Record<Language, Record<string, string>> = {
  en: {
    home: 'Home',
    courses: 'Courses',
    learn: 'Learn',
    instructors: 'Instructors',
    exams: 'Exams',
    store: 'Store',
    result: 'Result',
    login: 'Login / Sign in',
    loginShort: 'Login',
    admin: 'Admin',
    profile: 'My Profile',
    enrolledCourses: 'Enrolled Courses',
    examAnalytics: 'Exam Results & Analytics',
    adminPanel: 'Admin Panel',
    logout: 'Log Out',
    languageLabel: 'বাংলা',
    switchLanguage: 'Switch language',
    browseCourses: 'Browse courses',
    allExams: 'All exams',
    courseProgress: 'Course progress',
    continueLearning: 'Continue learning',
    availableExams: 'Available exams',
    public: 'Public',
    private: 'Private',
    search: 'Search',
    preview: 'Preview',
    getNow: 'Get Now',
    explore: 'Explore',
    viewDetails: 'View details',
    writeReview: 'Write a Student Review',
    cancel: 'Cancel',
    publishReview: 'Publish Review',
    syllabus: 'View syllabus',
    enterClass: 'Enter class',
    academicPrograms: 'Academic & admission programs',
    catalogTitle: 'Find the class that moves you forward.',
    catalogDescription: 'Focused courses, trusted mentors, and a clear path from your next chapter to your biggest academic goal.',
    browseStudyPath: 'Browse by study path',
    coursesAvailable: 'courses available',
    searchCoursesTeachers: 'Search courses or teachers...',
    curatedGoals: 'Curated for your goals',
    chooseNextCourse: 'Choose your next course',
    yourLearningSpace: 'Your learning space',
    keepGoing: 'Keep going',
    learningDescription: 'Pick up where you left off, join your next class, or test what you know.',
    activePrograms: 'Active programs',
    subjectTracks: 'Subject tracks',
    examsTaken: 'Exams taken',
    yourClassroom: 'Your classroom',
    unlimitedAccess: '24/7 unlimited access',
    noEnrolledCourses: 'No enrolled courses yet',
    classroomReady: 'Your classroom is ready when you are. Enroll in a program to access live classes, notes, and practice exams.',
    exploreCourses: 'Explore Courses',
    discoverPrograms: 'Discover new programs',
    practiceResults: 'Practice and track results',
    accountEnrollments: 'Account and enrollments',
    facultyEyebrow: 'The people behind the progress',
    facultyTitle: 'Learn from mentors who make hard things click.',
    facultyDescription: 'Meet the educators helping students build durable concepts, sharper problem-solving skills, and confidence for what comes next.',
    expertMentors: 'Expert mentors',
    subjectAreas: 'Subject areas',
    learnersReached: 'Learners reached',
    findYourGuide: 'Find your guide',
    teachingFaculty: 'Our teaching faculty',
    programsAcrossFaculty: 'programs across the faculty',
    practiceWithPurpose: 'Practice with purpose',
    examHubTitle: 'Test what you know. Find what to improve.',
    examHubDescription: 'Take chapter-wise exams, compare your pace on the leaderboard, and turn every attempt into a smarter study plan.',
    totalTests: 'Total tests',
    questions: 'Questions',
    waysToPractice: 'Ways to practice',
    chooseAssessment: 'Choose an assessment',
    examsMatch: 'exams match your view',
    examAssessments: 'assessments',
    studyShelf: 'The study shelf',
    storeTitle: 'Better notes for the moments that matter.',
    storeDescription: 'Practical formula sheets, visual notes, and focused workbooks made to make revision faster and concepts stick longer.',
    resources: 'Resources',
    pagesOfHelp: 'Pages of help',
    avgRating: 'Avg. rating',
    browseMaterials: 'Browse study materials',
    resourcesAvailable: 'resources available',
    curatedRevision: 'Curated revision tools',
    pickResource: 'Pick your next resource',
    officialPortal: 'Official result portal',
    verifiedProgress: 'Your progress, verified.',
    resultDescription: 'Find your Shikhor performance record or verify your official board result in a few simple steps.',
    shikhorExamResult: 'Shikhor Exam Result',
    modelTests: 'Model tests and mock exams',
    boardResult: 'Board Result',
    boardExams: 'HSC, SSC and equivalent exams',
    sortBy: 'Sort by',
    popular: 'Popular',
    rating: 'Rating',
    priceLow: 'Price: Low',
    priceHigh: 'Price: High',
    results: 'results',
    noCourses: 'No courses match your filter',
    tryAnother: 'Try selecting a different category or search term.',
    resetFilters: 'Reset filters',
    students: 'Students',
    teachers: 'Teachers',
    videos: 'Videos',
    onlineCourse: 'Online Course',
    batchesOngoing: 'Online batches are ongoing!',
    bookSeat: 'Book your seat now!',
    seeAllCourses: 'See All Courses',
    seeStats: 'See the stats!',
    trustBuilding: 'The trust we are building!',
    searchExams: 'Search by chapter or subject...',
    chooseLearningPath: 'Choose Your Learning Path',
    learningPathDescription: 'Discover diverse courses across multiple disciplines designed to help you excel in your academic and admission journey.',
    questionsEnrollment: 'Have questions about course curriculum or enrollment?',
    counselorAvailability: 'Our student counselor team is available 10:00 AM - 10:00 PM daily.',
    call: 'Call',
    more: 'more',
    enroll: 'Enroll',
    featuredBatchesEyebrow: 'Featured learning programs',
    featuredBatchesTitle: 'Popular batches for your next breakthrough.',
    featuredBatchesDescription: 'Explore carefully selected programs with trusted mentors, practical support, and a clear route to your academic goals.',
    viewAllBatches: 'View all batches',
    sortPrograms: 'Sort programs',
    categoryAll: 'All programs',
    categoryHSC: 'HSC',
    categorySSC: 'SSC',
    categoryAdmission: 'Admission',
    categoryCombo: 'Combo',
    categorySkill: 'Skills',
    topPick: 'Top pick',
    newProgram: 'New program',
    curatedProgram: 'Curated program',
    selectedProgram: 'Featured right now',
    enrolledLabel: 'enrolled',
    learningModules: 'learning modules',
    learnAtYourPace: 'Learn at your pace',
    startingFrom: 'Starting from',
    off: 'OFF',
    morePopularBatches: 'More popular batches',
    showMore: 'Show more',
    showLess: 'Show less',
    featuredEmpty: 'No featured batches yet',
    featuredEmptyDescription: 'New programs will appear here as soon as they are published.',
    learningLibrary: 'Your learning library',
    searchMyCourses: 'Search your courses...',
    allProgramsFilter: 'All programs',
    inProgress: 'In progress',
    completed: 'Completed',
    noMatchingCourses: 'No courses match your view',
    clearSearch: 'Clear search',
    focusCourse: 'Focus course',
    continueCourse: 'Continue course',
    markLessonComplete: 'Mark next lesson complete',
    nextLesson: 'Next lesson',
    studyRhythm: 'Your study rhythm',
    keepYourMomentum: 'Keep your momentum going',
    weeklyGoal: 'Weekly goal',
    weeklyGoalDescription: 'Complete one more lesson to stay on track this week.',
    recentActivity: 'Recent activity',
    noExamAttempts: 'No exam attempts yet',
    viewResults: 'View results',
    activeStatus: 'Active',
    allCaughtUp: 'All caught up',
    getStarted: 'Get started',
    lessonsLabel: 'lessons',
    modulesLabel: 'modules',
    gridView: 'Grid view',
    listView: 'List view',
    previousSlide: 'Previous slide',
    nextSlide: 'Next slide',
    goToSlide: 'Go to slide',
    overview: 'Overview',
    demoClass: 'Demo Class',
    reviews: 'Reviews',
    comboInstructors: 'Combo Instructors',
    comboDescription: 'Combo Description',
    courseFeatures: 'Course Features & Offerings',
    detailedSyllabus: 'Detailed Syllabus Breakdown',
    freeDemoClasses: 'Free Interactive Demo Classes',
    sampleLectures: 'Available Sample Lectures',
    demoDescription: 'Watch our sample masterclasses to experience our teaching methodology before enrolling.',
    openVideoPlayer: 'Open in Video Player',
    allCourses: 'All Courses',
    examsRoutine: 'Exams Routine',
    storeNotes: 'Store: E-Books & Notes',
  },
  bn: {
    home: 'হোম',
    courses: 'কোর্সসমূহ',
    learn: 'শিখুন',
    instructors: 'শিক্ষকবৃন্দ',
    exams: 'পরীক্ষা',
    store: 'স্টোর',
    result: 'ফলাফল',
    login: 'লগইন / সাইন ইন',
    loginShort: 'লগইন',
    admin: 'অ্যাডমিন',
    profile: 'আমার প্রোফাইল',
    enrolledCourses: 'এনরোল করা কোর্স',
    examAnalytics: 'পরীক্ষার ফলাফল ও বিশ্লেষণ',
    adminPanel: 'অ্যাডমিন প্যানেল',
    logout: 'লগ আউট',
    languageLabel: 'English',
    switchLanguage: 'ভাষা পরিবর্তন করুন',
    browseCourses: 'কোর্স দেখুন',
    allExams: 'সব পরীক্ষা',
    courseProgress: 'কোর্সের অগ্রগতি',
    continueLearning: 'শেখা চালিয়ে যান',
    availableExams: 'উপলভ্য পরীক্ষা',
    public: 'সবার জন্য',
    private: 'ব্যক্তিগত',
    search: 'খুঁজুন',
    preview: 'প্রিভিউ',
    getNow: 'এখনই নিন',
    explore: 'দেখুন',
    viewDetails: 'বিস্তারিত দেখুন',
    writeReview: 'শিক্ষার্থীর মতামত লিখুন',
    cancel: 'বাতিল',
    publishReview: 'মতামত প্রকাশ করুন',
    syllabus: 'সিলেবাস দেখুন',
    enterClass: 'ক্লাসে প্রবেশ করুন',
    academicPrograms: 'একাডেমিক ও ভর্তি প্রোগ্রাম',
    catalogTitle: 'আপনার এগিয়ে যাওয়ার সঠিক ক্লাসটি খুঁজুন।',
    catalogDescription: 'মনোযোগী কোর্স, অভিজ্ঞ মেন্টর এবং আপনার একাডেমিক লক্ষ্যে পৌঁছানোর পরিষ্কার পথ।',
    browseStudyPath: 'স্টাডি পাথ বেছে নিন',
    coursesAvailable: 'টি কোর্স উপলভ্য',
    searchCoursesTeachers: 'কোর্স বা শিক্ষক খুঁজুন...',
    curatedGoals: 'আপনার লক্ষ্যের জন্য বাছাই করা',
    chooseNextCourse: 'আপনার পরবর্তী কোর্স বেছে নিন',
    yourLearningSpace: 'আপনার লার্নিং স্পেস',
    keepGoing: 'এগিয়ে চলুন',
    learningDescription: 'যেখান থেকে থেমেছিলেন সেখান থেকেই শুরু করুন, পরবর্তী ক্লাসে যোগ দিন বা নিজের প্রস্তুতি যাচাই করুন।',
    activePrograms: 'চলমান প্রোগ্রাম',
    subjectTracks: 'বিষয় ট্র্যাক',
    examsTaken: 'দেওয়া পরীক্ষা',
    yourClassroom: 'আপনার ক্লাসরুম',
    unlimitedAccess: '২৪/৭ আনলিমিটেড অ্যাক্সেস',
    noEnrolledCourses: 'এখনও কোনো কোর্সে এনরোল করা নেই',
    classroomReady: 'আপনার ক্লাসরুম প্রস্তুত। লাইভ ক্লাস, নোট এবং প্র্যাকটিস পরীক্ষা পেতে একটি প্রোগ্রামে এনরোল করুন।',
    exploreCourses: 'কোর্স দেখুন',
    discoverPrograms: 'নতুন প্রোগ্রাম দেখুন',
    practiceResults: 'প্র্যাকটিস ও ফলাফল ট্র্যাক করুন',
    accountEnrollments: 'অ্যাকাউন্ট ও এনরোলমেন্ট',
    facultyEyebrow: 'যারা আপনার অগ্রগতির পেছনে',
    facultyTitle: 'যেসব মেন্টর কঠিন বিষয়কে সহজ করে তোলেন তাদের কাছ থেকে শিখুন।',
    facultyDescription: 'ধারণা পরিষ্কার, সমস্যা সমাধান এবং আত্মবিশ্বাস গড়ে তুলতে যেসব শিক্ষক শিক্ষার্থীদের সাহায্য করছেন তাদের সাথে পরিচিত হন।',
    expertMentors: 'অভিজ্ঞ মেন্টর',
    subjectAreas: 'বিষয় ক্ষেত্র',
    learnersReached: 'শিক্ষার্থী পৌঁছেছে',
    findYourGuide: 'আপনার গাইড খুঁজুন',
    teachingFaculty: 'আমাদের শিক্ষকবৃন্দ',
    programsAcrossFaculty: 'টি প্রোগ্রাম',
    practiceWithPurpose: 'উদ্দেশ্য নিয়ে প্র্যাকটিস করুন',
    examHubTitle: 'আপনি কী জানেন যাচাই করুন। কোথায় উন্নতি দরকার খুঁজে নিন।',
    examHubDescription: 'অধ্যায়ভিত্তিক পরীক্ষা দিন, লিডারবোর্ডে নিজের গতি তুলনা করুন এবং প্রতিটি প্রচেষ্টাকে স্মার্ট স্টাডি প্ল্যানে বদলে দিন।',
    totalTests: 'মোট পরীক্ষা',
    questions: 'প্রশ্ন',
    waysToPractice: 'প্র্যাকটিসের ধরন',
    chooseAssessment: 'একটি মূল্যায়ন বেছে নিন',
    examsMatch: 'টি পরীক্ষা আপনার ভিউতে',
    examAssessments: 'মূল্যায়ন',
    studyShelf: 'স্টাডি শেলফ',
    storeTitle: 'গুরুত্বপূর্ণ মুহূর্তের জন্য আরও ভালো নোট।',
    storeDescription: 'রিভিশন দ্রুত করতে এবং ধারণা মনে রাখতে তৈরি ফর্মুলা শিট, ভিজ্যুয়াল নোট ও ফোকাসড ওয়ার্কবুক।',
    resources: 'রিসোর্স',
    pagesOfHelp: 'সহায়ক পৃষ্ঠা',
    avgRating: 'গড় রেটিং',
    browseMaterials: 'স্টাডি ম্যাটেরিয়াল দেখুন',
    resourcesAvailable: 'টি রিসোর্স উপলভ্য',
    curatedRevision: 'বাছাই করা রিভিশন টুল',
    pickResource: 'আপনার পরবর্তী রিসোর্স বেছে নিন',
    officialPortal: 'অফিশিয়াল রেজাল্ট পোর্টাল',
    verifiedProgress: 'আপনার অগ্রগতি, যাচাই করা।',
    resultDescription: 'কয়েকটি সহজ ধাপে আপনার শিখর পারফরম্যান্স রেকর্ড খুঁজুন বা অফিসিয়াল বোর্ড রেজাল্ট যাচাই করুন।',
    shikhorExamResult: 'শিখর পরীক্ষার ফলাফল',
    modelTests: 'মডেল টেস্ট ও মক পরীক্ষা',
    boardResult: 'বোর্ড রেজাল্ট',
    boardExams: 'এইচএসসি, এসএসসি ও সমমান পরীক্ষা',
    sortBy: 'সাজান',
    popular: 'জনপ্রিয়',
    rating: 'রেটিং',
    priceLow: 'দাম: কম থেকে',
    priceHigh: 'দাম: বেশি থেকে',
    results: 'টি ফলাফল',
    noCourses: 'এই ফিল্টারে কোনো কোর্স নেই',
    tryAnother: 'অন্য ক্যাটাগরি বা সার্চ টার্ম ব্যবহার করুন।',
    resetFilters: 'ফিল্টার রিসেট করুন',
    students: 'শিক্ষার্থী',
    teachers: 'শিক্ষক',
    videos: 'ভিডিও',
    onlineCourse: 'অনলাইন কোর্স',
    batchesOngoing: 'অনলাইন ব্যাচ চলছে!',
    bookSeat: 'এখনই আপনার সিট বুক করুন!',
    seeAllCourses: 'সব কোর্স দেখুন',
    seeStats: 'পরিসংখ্যান দেখুন!',
    trustBuilding: 'আমরা যে আস্থা তৈরি করছি!',
    searchExams: 'অধ্যায় বা বিষয় দিয়ে খুঁজুন...',
    chooseLearningPath: 'আপনার লার্নিং পাথ বেছে নিন',
    learningPathDescription: 'একাডেমিক ও ভর্তি প্রস্তুতিতে এগিয়ে যেতে বিভিন্ন বিষয়ে সাজানো কোর্স আবিষ্কার করুন।',
    questionsEnrollment: 'কোর্স কারিকুলাম বা এনরোলমেন্ট নিয়ে প্রশ্ন আছে?',
    counselorAvailability: 'আমাদের স্টুডেন্ট কাউন্সেলর টিম প্রতিদিন সকাল ১০টা থেকে রাত ১০টা পর্যন্ত কাজ করে।',
    call: 'কল করুন',
    more: 'জন শিক্ষক',
    enroll: 'এনরোল করুন',
    featuredBatchesEyebrow: 'বিশেষ লার্নিং প্রোগ্রাম',
    featuredBatchesTitle: 'আপনার পরবর্তী সাফল্যের জন্য জনপ্রিয় ব্যাচ।',
    featuredBatchesDescription: 'অভিজ্ঞ মেন্টর, প্রয়োজনীয় সহায়তা এবং একাডেমিক লক্ষ্যে পৌঁছানোর পরিষ্কার পথসহ বাছাই করা প্রোগ্রামগুলো দেখুন।',
    viewAllBatches: 'সব ব্যাচ দেখুন',
    sortPrograms: 'প্রোগ্রাম সাজান',
    categoryAll: 'সব প্রোগ্রাম',
    categoryHSC: 'এইচএসসি',
    categorySSC: 'এসএসসি',
    categoryAdmission: 'ভর্তি প্রস্তুতি',
    categoryCombo: 'কম্বো',
    categorySkill: 'দক্ষতা',
    topPick: 'সেরা পছন্দ',
    newProgram: 'নতুন প্রোগ্রাম',
    curatedProgram: 'বাছাই করা প্রোগ্রাম',
    selectedProgram: 'এই মুহূর্তের বিশেষ প্রোগ্রাম',
    enrolledLabel: 'জন এনরোল করেছেন',
    learningModules: 'টি লার্নিং মডিউল',
    learnAtYourPace: 'নিজের গতিতে শিখুন',
    startingFrom: 'শুরু হচ্ছে',
    off: 'ছাড়',
    morePopularBatches: 'আরও জনপ্রিয় ব্যাচ',
    showMore: 'আরও দেখুন',
    showLess: 'কম দেখুন',
    featuredEmpty: 'এখনও কোনো বিশেষ ব্যাচ নেই',
    featuredEmptyDescription: 'নতুন প্রোগ্রাম প্রকাশিত হলে সেগুলো এখানে দেখা যাবে।',
    learningLibrary: 'আপনার লার্নিং লাইব্রেরি',
    searchMyCourses: 'আপনার কোর্স খুঁজুন...',
    allProgramsFilter: 'সব প্রোগ্রাম',
    inProgress: 'চলমান',
    completed: 'সম্পন্ন',
    noMatchingCourses: 'এই ভিউতে কোনো কোর্স নেই',
    clearSearch: 'সার্চ মুছে ফেলুন',
    focusCourse: 'কোর্সে ফোকাস করুন',
    continueCourse: 'কোর্স চালিয়ে যান',
    markLessonComplete: 'পরবর্তী লেসন সম্পন্ন করুন',
    nextLesson: 'পরবর্তী লেসন',
    studyRhythm: 'আপনার স্টাডি রিদম',
    keepYourMomentum: 'আপনার ধারাবাহিকতা ধরে রাখুন',
    weeklyGoal: 'সাপ্তাহিক লক্ষ্য',
    weeklyGoalDescription: 'এই সপ্তাহে ট্র্যাকে থাকতে আরও একটি লেসন সম্পন্ন করুন।',
    recentActivity: 'সাম্প্রতিক কার্যক্রম',
    noExamAttempts: 'এখনও কোনো পরীক্ষা দেওয়া হয়নি',
    viewResults: 'ফলাফল দেখুন',
    activeStatus: 'চলমান',
    allCaughtUp: 'সব সম্পন্ন হয়েছে',
    getStarted: 'শুরু করুন',
    lessonsLabel: 'টি লেসন',
    modulesLabel: 'টি মডিউল',
    gridView: 'গ্রিড ভিউ',
    listView: 'লিস্ট ভিউ',
    previousSlide: 'আগের স্লাইড',
    nextSlide: 'পরের স্লাইড',
    goToSlide: 'স্লাইডে যান',
    overview: 'ওভারভিউ',
    demoClass: 'ডেমো ক্লাস',
    reviews: 'রিভিউ',
    comboInstructors: 'কম্বো শিক্ষকবৃন্দ',
    comboDescription: 'কম্বো সম্পর্কে',
    courseFeatures: 'কোর্সের সুবিধা ও অফার',
    detailedSyllabus: 'বিস্তারিত সিলেবাস',
    freeDemoClasses: 'ফ্রি ইন্টার‌্যাক্টিভ ডেমো ক্লাস',
    sampleLectures: 'উপলভ্য স্যাম্পল লেকচার',
    demoDescription: 'এনরোল করার আগে আমাদের পড়ানোর পদ্ধতি বুঝতে স্যাম্পল মাস্টারক্লাস দেখুন।',
    openVideoPlayer: 'ভিডিও প্লেয়ারে খুলুন',
    allCourses: 'সব কোর্স',
    examsRoutine: 'পরীক্ষার রুটিন',
    storeNotes: 'স্টোর: ই-বুক ও নোট',
  },
};

interface LanguageContextValue {
  language: Language;
  setLanguage: (language: Language) => void;
  toggleLanguage: () => void;
  t: (key: string, fallback?: string) => string;
}

const LanguageContext = createContext<LanguageContextValue | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>(() => {
    if (typeof window === 'undefined') return 'en';
    return window.localStorage.getItem('shikhor-language') === 'bn' ? 'bn' : 'en';
  });

  useEffect(() => {
    window.localStorage.setItem('shikhor-language', language);
    document.documentElement.lang = language;
  }, [language]);

  const value = useMemo<LanguageContextValue>(() => ({
    language,
    setLanguage,
    toggleLanguage: () => setLanguage((current) => current === 'en' ? 'bn' : 'en'),
    t: (key, fallback) => translations[language][key] || fallback || key,
  }), [language]);

  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>;
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) throw new Error('useLanguage must be used within a LanguageProvider');
  return context;
}
